import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "America Amigas App",
  description: "Generated by loldev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
